// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Status struct {
	Ts         time.Time
	Url        string
	StatusCode int64
	ResponseMs int64
}
